### ISSUE TITLE
test email

### ISSUE THREAD

**Issue by niutonghz** [jomozz/gitskills#1]
email

**Comment by jomozz** [comment]
sdfsf













At 2022-03-15 16:10:25, "niutonghz" ***@***.***> wrote:

email

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jomozz** [comment]
Hello, my name is Chen Xiaofang and my English name is Anna. Because the founding team of our company has worked in the Internet industry for more than 10 years and has a deep customer relationship foundation, since we started our business in 2019, many customers or friends need our services, so we didn't do external publicity.




The attachment is the business license of our company. Please check it.










At 2022-03-15 16:10:25, "niutonghz" ***@***.***> wrote:

email

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jomozz** [comment]
Hello, Because the founding team of our company has worked in the Internet industry for more than 10 years and has a deep customer relationship foundation, since we started our business in 2019, many customers or friends need our services, so we didn't do external publicity.







At 2022-03-15 16:10:25, "niutonghz" ***@***.***> wrote:

email

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jomozz** [comment]
Hello, my name is Chen Xiaofang and my English name is Anna. Because the founding team of our company has worked in the Internet industry for more than 10 years and has a deep customer relationship foundation, since we started our business in 2019, many customers or friends need our services, so we didn't do external publicity.




The attachment is the business license of our company. Please check it.













At 2022-03-15 16:10:25, "niutonghz" ***@***.***> wrote:

email

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jomozz** [comment]
Hello, my name is Chen Xiaofang and my English name is Anna. Because the founding team of our company has worked in the Internet industry for more than 10 years and has a deep customer relationship foundation, since we started our business in 2019, many customers or friends need our services, so we didn't do external publicity.




At 2022-03-15 16:10:25, "niutonghz" ***@***.***> wrote:

email

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
